services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret_password
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
