services:
  server:
    image: blog-server-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: blog-server-dev
    environment:
      - DATABASE_URL=postgres://postgres:secret_password@postgres:5432/postgres
      - PORT=3000
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret_password
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
